version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  bundle:
    image: busybox
    volumes:
      - /usr/local/bundle

  web:
    build: .
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; rails server -p 3000 -b 0.0.0.0" ]
    volumes:
      - .:/usr/src/my_app
    volumes_from:
      - bundle
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_HOST=db
    depends_on:
      - db
      - bundle
